name = "Hugo Profile"
license = "MIT"
licenselink = "https://github.com/gurusabarish/hugo-profile/blob/master/LICENSE"
description = "A high performance and mobile first hugo template for personal portfolio and blog."
homepage = "https://github.com/roggrt"
demosite = "https://roggrt.netlify.app"
tags = ["Responsive","Blog", "Portfolio", "Personal", "Software", "Cuenca"]
min_version = "0.68.0"

[author]
  name = "roggrt"
  homepage = "https://www.linkedin.com/in/roggrt/"
