baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Roggrt Dev"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "Desarrollo y diseño de sitios web, software, marketing digital y más en Ecuador, empieza a digitalizar tu negocio y ponte al alcance de mas personas"

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Roger Rojas"
  namecolor: ffc107
  profession: "Software Developer"
  github: "https://github.com/roggrt"
  gitlab: "https://gitlab.com/roggrt"
  linkedin: "https://www.linkedin.com/in/roggrt/"
  twitter: "https://twitter.com/roggertzy"
  instagram: "https://instagram.com/roggertzy"
  facebook: "https://facebook.com"

  # About
  disable_about: false
  descripe_l1_person: "Hola, soy Roger, un desarrollador de software. Desarrollo sitios web funcionales y modernas con las mejores tecnologías del momento, lo que hace que estas luzcan bien, sean funcionales y cumplan con su proposito."
  descripe_l2_person: "Desarrollo tiendas en línea, páginas informativas, me adapto a tu presupuesto, puedes ver parte de mi trabajo [aquí](#projects)"
  skills:
    - name: Html/Css
      percentage: 90
    - name: Javascript
      percentage: 85
    - name: Java
      percentage: 80
    - name: Python
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Grupo Ortiz"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Soporte en sistemas"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Desarrollo de microservicios con spring.
        - point: Control de usuarios y manejo del windows server.
    - company: "Commercejs"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Desarrollo FullStack"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Desarrollo de backend para productos en bases de datos.
        - point: Integracion de codigo fuente y refactorizacion.
    - company: "PcSystems"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Soporte en sistemas"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Mantenimiento y reparación de equipo de cómputo.
        - point: Manejo de pagina web de la empresa y desarrollo de tienda en línea.

  # Education
  disable_education: false
  education:
    - degree: "Tecnologias"
      branch: "Software"
      university: "Tecnologico del Azuay"
      startedyear: "2018"
      graduation: "2021"
    - degree: "Programador"
      branch: "Software"
      university: "Michigan University"
      startedyear: "2018"
      graduation: "2019"

  # Projects
  disable_projects: true
  projects:
    - name: "Proyectos"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Desarrollo web, aplicaciones Java, Manejo de metodologias de desarrollo de software"

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: Siempre estoy pendiente a mi inbox +593963922332 y correo. Si tienes una duda o tan solo quieres pasar a saludar, mandame un mensaje o correo, trataré de responderte lo antes posible!
  email: "roggrt@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
